Loop$ improvements: (1) ignorable is implicit in lambda$; (2) locals/globals switch in fancy loops; (3) :doc loop$; Special Conjectures for guards improved with (4) member-equal instead of mempos and with (5) warrant hypotheses,
Although J and I have lots of discussion about the design of these
loop$ improvements, implementation work for (1) through (4) were
essentially J's work and for (5) was essentially mine.

(1) Loop$ bodies continue to generate lambda$ expressions.  Formerly,
an ignorable declaration for the lambda$ formals was generated for
these lambda$ expressions.  Now they are not; instead, translation of
lambda$ to a quoted lambda is what generates the ignorable
declaration.  The benefit is that one no longer sees distracting
ignorable declarations in untranslated output arising from loops.

(2) Fancy loops continue to generate lambda$ expressions with two
arguments, representing loop variables and "global" variables not
bound by the loop variables.  Formerly the lambda$ parameter list was
(locals globals); those have been switched and renamed, resulting in
(LOOP$-GVARS LOOP$-IVARS), which is more intuitive (especially given
other aspects of loop$ translation).

(3) Formerly, :doc loop$ was little more than a stub.  That
documentation is now quite extensive.

(4) The so-called "Special Conjectures" are guard proof obligations to
support the use of Common Lisp loop to execute loop$ expressions in
function bodies during top-level evaluation.  These existed before;
but now, hypotheses about member-equal replace hypotheses about
mempos.  The new book books/projects/apply/mempos.lisp can support
useful reasoning about mempos, including fancy loops.

(5) Formerly it was necessary to specify warrant hypotheses in guards,
which defeated evaluation during proofs.  Consider the following
example, where at the end we attempt a proof using evaluation, by
disabling a definition to prevent proof by rewriting.

(include-book "projects/apply/top" :dir :system)
(defun$ double (n)
  (declare (xargs :guard (integerp n)))
  (+ n n))
(defun sum-doubles (lst)
  (declare (xargs :guard (and (warrant double) ; to be removed
                              (integer-listp lst))))
  (loop$ for x of-type integer in lst sum (double x)))
; Fails:
(thm (implies (warrant double)
              (equal (sum-doubles '(1 2 3)) 12))
     :hints (("Goal" :in-theory (disable (:d sum-doubles)))))

The thm fails because the attempt to execute sum-doubles fails with an
error: the guard cannot be evaluated during the proof.  (Remarks.  (a)
Warrants are constrained functions and need attachments to evaluate,
which aren't available during proofs.  (b) Perhaps guard evaluation
failure shouldn't defeat execution but should just punt to *1*
evaluation.  That may be future work.)  Before this change, the
hypothesis (warrant double) was necessary for guard verification of
sum-doubles.  Now it is no longer needed, because Special Conjectures
include warrant hypotheses.

Note: In addition to changes (1) through (5) there are a few tweaks,
for example in error messages involving ignore and ignorable
declarations.

In addition to running a clean regression-everything, I also built a
#+acl2-devel executable and went through the process described in a
comment in the source definition of *system-verify-guards-alist*.