Fixed an iprinting bug.
Added new book (books/tools/equality-with-hons-copy.lisp) for
reasoning about equality of large terms, which David has used -- no
small example yet, hence no documentation yet.

Quoting :doc note-7-3:

  A bug has been fixed that could cause hard Lisp error when using the
  [iprint] utility. Specifically, calling [set-iprint] with a small
  :hard-bound could cause a hard Lisp error during ``rollover'', as
  with the following example.

    (set-iprint :reset-enable :hard-bound 200)
    (set-iprint t :hard-bound 1000)
    (f-get-global 'iprint-ar state)
    (set-evisc-tuple (evisc-tuple 3 4 nil nil) :iprint t :sites :all)
    (thm (equal (append (append x y) x y x y x y x y)
                (append x y x y x y x y x y)))
    (pso)
    (pso)
    (pso)

  Thanks to David Rager for bringing this bug to our attention and for
  describing how it occurred in his environment. The fix is to
  convert the argument t of [set-iprint] to :reset-enable when
  keyword argument :hard-bound is supplied.

Note that there are still at least two bugs involving iprinting!  My
plan is to fix those after Thursday.  Both arise with fms-to-string
and related "-to-string" functions, and both are related to the way
those functions cope with iprinting using the constant
*fmt-control-defaults*.  Here is a brief description.

One remaining bug is a Lisp hard error, as illustrated by the following
example.

(defun tree (n x)
  (declare (xargs :guard (natp n)))
  (if (zp n)
      x
      (let ((sub (tree (1- n) x)))
	   (cons sub sub))))

(set-iprint :reset-enable :hard-bound 20)

; and then:

ACL2 !>(fms-to-string "~x0~%" (list (cons #\0 (tree 10 nil)))
               :evisc-tuple (evisc-tuple 3 4 nil nil))

***********************************************
************ ABORTING from raw Lisp ***********
Error:  The value NIL is not of the expected type NUMBER.
***********************************************

The other bug could be viewed as a soundness bug, were it not for the
fact that fms-to-string etc. are macros generating calls of functions
in :program mode that cannot be put into :logic mode.  Consider this
session, where fms-to-string does not take state -- so (f) should
always return the same value!

(defun f ()
  (declare (xargs :guard t :mode :program))
  (fms-to-string "~x0~%"
                 (list (cons #\0 (make-list 10)))
                 :evisc-tuple (evisc-tuple 3 4 nil nil)))

; Then:

ACL2 !>(f)
"
(NIL NIL NIL NIL ...)
"
ACL2 !>(set-iprint t)

ACL2 Observation in SET-IPRINT:  Iprinting has been enabled.
ACL2 !>(f)
"
(NIL NIL NIL NIL . #@1#)
"
ACL2 !>