[ACL2s] Update to cgen so that it ignores raw lisp errors during cgen, to the extent possible.   This change allows us to hide any errors that may be generated   during the counterexample generation process. The idea of   counterexample generation is to look for errors in the form of   counterexamples and to report such errors to users of the theorem   prover, but to otherwise introduce minimal disruptions in the   theorem proving process.
  Why might counterexample generation disrupt the theorem proving
  process? Well, consider evaluating a function that is exponential
  time, say fib, on large numbers. We do not want this process to use
  significant resources, such as time and space. The use of timeouts
  helps to ameliorate this issue. But, it will not help if we exhaust
  memory or if common lisp throws an error. Here is an example from
  ACL2 built using SBCL. First, some trivial theorems.

  (defthm foo (implies (natp  x) (natp (expt 2 x))))
  (in-theory (disable natp))
  (defthm bar (implies (natp  x) (natp (expt 2 (expt 2 x)))))

  Now, since bar is a theorem, what we might expect is that evaluating
  the body of bar, after replacing the variables by any constant will
  evaluate to t. Let's try it.

  (let ((x 1000000)) (implies (natp  x) (natp (expt 2 (expt 2 x)))))

  That leads to an error. Here is what SBCL reports.

  ************ ABORTING from raw Lisp ***********
  ********** (see :DOC raw-lisp-error) **********
  Error:  can't represent result of left shift
  ***********************************************

  The issue is that SBCL, in the process of evaluating expt evaluates
  bignum-ashift-left, which checks that we are not shifting by a very
  large number, since that will lead to a number not representable
  with existing memory. That check leads to the above error. Note that
  the following thm leads to a similar error:

  (thm (natp (expt 2 (expt 2 1000000))))

  As does the following.

  (test? (natp (expt 2 (expt 2 1000000))))

  This is the kind of thing that can happen when we are generating
  counterexamples.

  Note that we can prove the above and bypass evaluation, eg, with this:

  (thm (natp (expt 2 (expt 2 1000000)))
    :hints ((Goal :use (:instance bar (x 1000000)))))

  Anyway, the current implementation will catch such errors, but it is
  still possible for fatal, non-recoverable errors to occur.