Updated copyrights.  Updated saved_acl2 for CMUCL to use maximum heap for CMU Common Lisp snapshot-2016-01 and beyond.  Avoided x86 books for CMUCL.
Quoting :doc note-7-2:

  (CMUCL only) Updated saved_acl2 for CMUCL to use maximum heap for CMU
  Common Lisp snapshot-2016-01 and beyond. Thanks to Raymond Toy for
  updating CMUCL such that one can specify with -dynamic-space-size 0
  that the maximum heap is used.

Avoided CMUCL in x86isa books because of this error (if 64-bit CMUCL
becomes available then perhaps this won't be necessary):

  Error:  Heap (dynamic space) overflow".