Restored books/workshops/1999/calculus/book/outline/.  Fixed proof that was stalling in GCL.
The directory books/workshops/1999/calculus/book/outline/ existed in
the svn repo but is apparently missing from the git repo, I think
because git doesn't add empty directories.  Without that directory, I
got the following error during an attempted ACL2(r) regression based
on GCL CLtL1.

Printing depth 1...
Error: ERROR "Cannot create the file outline/outline.1."
Fast links are on: do (si::use-fast-links nil) for debugging
Signalled by LP.
Backtrace: eval > lp > system::break-level-for-acl2 > let* > unless > SYSTEM::SIMPLE-BACKTRACE
ACL2(r) !>
Exiting the ACL2 read-eval-print loop.  To re-enter, execute (LP).

I've fixed this by arranging for "make" to create the directory; also,
I've arranged to clean outline/.